version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: crinity_django/nginx
        restart: always
        ports:
          - "9000:8000"
        volumes:
          - ./django/crinity_django:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build: ./django/crinity_django
        image: crinity_django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./django/crinity_django:/srv/docker-server
          - ./log:/var/log/uwsgi
